//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::System.Reflection.AssemblyVersionAttribute("1.0.0.0")]
[assembly: global::System.Reflection.AssemblyProductAttribute("Robcio")]
[assembly: global::System.Reflection.AssemblyTitleAttribute("Robcio")]
[assembly: global::Microsoft.Dss.Core.Attributes.ServiceDeclarationAttribute(global::Microsoft.Dss.Core.Attributes.DssServiceDeclaration.Transform, SourceAssemblyKey="Robcio.Y2012.M07, Version=1.0.0.0, Culture=neutral, PublicKeyToken=8212bc3f397d79" +
    "f1")]
[assembly: global::System.Security.SecurityTransparentAttribute()]
[assembly: global::System.Security.SecurityRulesAttribute(global::System.Security.SecurityRuleSet.Level1)]

namespace Dss.Transforms.TransformRobcio {
    
    
    public class Transforms : global::Microsoft.Dss.Core.Transforms.TransformBase {
        
        static Transforms() {
            Register();
        }
        
        public static void Register() {
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddProxyTransform(typeof(global::com.bylica.robcio.Proxy.RobcioState), new global::Microsoft.Dss.Core.Attributes.Transform(com_bylica_robcio_Proxy_RobcioState_TO_com_bylica_robcio_RobcioState));
            global::Microsoft.Dss.Core.Transforms.TransformBase.AddSourceTransform(typeof(global::com.bylica.robcio.RobcioState), new global::Microsoft.Dss.Core.Attributes.Transform(com_bylica_robcio_RobcioState_TO_com_bylica_robcio_Proxy_RobcioState));
        }
        
        private static global::com.bylica.robcio.Proxy.RobcioState _cachedInstance0 = new global::com.bylica.robcio.Proxy.RobcioState();
        
        private static global::com.bylica.robcio.RobcioState _cachedInstance = new global::com.bylica.robcio.RobcioState();
        
        public static object com_bylica_robcio_Proxy_RobcioState_TO_com_bylica_robcio_RobcioState(object transformFrom) {
            return _cachedInstance;
        }
        
        public static object com_bylica_robcio_RobcioState_TO_com_bylica_robcio_Proxy_RobcioState(object transformFrom) {
            return _cachedInstance0;
        }
    }
}
